# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname qui
  namespace: flux-system
spec:
  targetNamespace: apps
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/apps/qui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  components:
    - ../../../../components/volsync/
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: qui
      VOLSYNC_CAPACITY: 2Gi
