---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: traefik
  values:
    image:
      registry: ghcr.io
      repository: traefik/traefik
      tag: v3.6.2
    deployment:
      replicas: 2
      podLabels:
        ingress.samoth.eu/prometheus: allow
        ingress.samoth.eu/lan: allow
        ingress.samoth.eu/cluster: allow
        egress.samoth.eu/cluster: allow
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: &igname traefik-internal
    providers:
      kubernetesIngress:
        ingressClass: *igname
    globalArguments: []
    ports:
      web:
        # make sure to update the network policy accordingly
        port: 8000
        expose:
          default: false
      websecure:
        # make sure to update the network policy accordingly
        port: 8443
        http3:
          enabled: true
        tls:
          domains:
            - main: "${INTERNAL_DOMAIN}"
              sans: ["*.${INTERNAL_DOMAIN}"]
      gittcp:
        port: 2222
        exposedPort: 2222
        protocol: TCP
        expose:
          default: true
        tls:
          enabled: false
    service:
      # required for dsr to work properly
      single: false
      annotations:
        lbipam.cilium.io/sharing-key: traefik-internal
        lbipam.cilium.io/ips: 192.168.0.44
        service.cilium.io/forwarding-mode: dsr
    priorityClassName: high-priority
    metrics:
      prometheus:
        # Need to be disabled otherwise flux-local fails
        disableAPICheck: true
        service:
          enabled: true
        serviceMonitor:
          enabled: true
    logs:
      access:
        enabled: true
        format: null
        filters:
          statuscodes: 500-599
