---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: traefik
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      registry: ghcr.io
      repository: traefik/traefik
      tag: v3.6.2
    deployment:
      replicas: 2
      podLabels:
        ingress.samoth.eu/prometheus: allow
        ingress.samoth.eu/kube-apiserver: allow
        egress.samoth.eu/kube-apiserver: allow
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: &igname traefik-external
    providers:
      kubernetesCRD:
        ingressClass: *igname
      kubernetesIngress:
        ingressClass: *igname
    globalArguments: []
    ingressRoute:
      dashboard:
        labels:
          external.traefik.samoth.eu/ingress: allow
    ports:
      web:
        # make sure to update the network policy accordingly
        port: 8000
        expose:
          default: false
      websecure:
        # make sure to update the network policy accordingly
        port: 8443
        exposedPort: 8443
        tls:
          domains:
            - main: "${EXTERNAL_DOMAIN}"
              sans: ["*.${EXTERNAL_DOMAIN}"]
    service:
      annotations:
        "lbipam.cilium.io/ips": "192.168.0.47"
    priorityClassName: high-priority
    metrics:
      prometheus:
        # Need to be disabled otherwise flux-local fails
        disableAPICheck: true
        service:
          enabled: true
        serviceMonitor:
          enabled: true
