apiVersion: v1
kind: Secret
metadata:
    name: harbor-redis-secret
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:gEAAecUIha8bTDYJ0MQn7gb1SHVcieWdAhEUlzPTG6I=,iv:RkXBUWl/ZR6WmkpEvt5fBksw/2B/riyBbhvaoE1mKwg=,tag:ofv+OiQA0P+t8QlutgSx8g==,type:str]
sops:
    age:
        - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUUdsK2szNUN0R09XZmdC
            M2gyWEdkUEdmckQyajlib1BDM01PNXdSaWt3CnhKakQwM2R2U0oyOGl4ZWlEcFRz
            eGEvbWRjTEU3Q0ZkdlU5K3JoMnZRVEUKLS0tIEV3dHlpTWE4Y3JzWTBVc0RkTnR0
            YUVRQXQ4Z0lmT0ZXdEJCbTlBQWF4eUUK1+iV+s2TrKFmda+KgL9ZdrKwAdovn9u2
            +8ac5uz2WS+SeHWOEG+n5OMUSpJx6vNjiMy6XqPj2e7Cuhk/g/HEVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T19:33:01Z"
    mac: ENC[AES256_GCM,data:FTKwJgd5mpIq0jZERGBwHSDzVto5DbkONHpFV6Q7zmA4ZIFS6gMBAMXrEoMCm7KxlyzctAdD8nMmJpLPxqBafjOhPopDowQvXdeohhXykVh/yCCJyrvUeoiw4Nqai+Sdo+mmOKQG/YgTg2UJfK1dBlCc5KZ0OllwZoYrMiY1keI=,iv:OO0SIng0inUuuitM68b8lBg/x+u0CxKWDFfnzJ+tEKQ=,tag:pXyJ8rXgzLNxF+JaZ4u9hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
