apiVersion: v1
kind: Secret
metadata:
  name: harbor-redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:2OkrFyxfW8rkY892a4cm2gu5mPdj0yn/s+YLPZ9qo20=,iv:lDFMxRJYZgkbbyuW40L3tAWSlquOUrT3dSN5Dc4mFjE=,tag:Ma6M77bEqrf+augeXfao6A==,type:str]
sops:
  age:
    - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUUdsK2szNUN0R09XZmdC
        M2gyWEdkUEdmckQyajlib1BDM01PNXdSaWt3CnhKakQwM2R2U0oyOGl4ZWlEcFRz
        eGEvbWRjTEU3Q0ZkdlU5K3JoMnZRVEUKLS0tIEV3dHlpTWE4Y3JzWTBVc0RkTnR0
        YUVRQXQ4Z0lmT0ZXdEJCbTlBQWF4eUUK1+iV+s2TrKFmda+KgL9ZdrKwAdovn9u2
        +8ac5uz2WS+SeHWOEG+n5OMUSpJx6vNjiMy6XqPj2e7Cuhk/g/HEVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T19:10:45Z"
  mac: ENC[AES256_GCM,data:egp2xI48pzrSOQV/DeKVsFzgESZNf6rDQ2ZGV1ZGWSalP7uwUYQ9TeNoki7BRNeqKeKeUs8AZmYMfuVkYg2IMZTYOl1D9jsEXWrk55n9zj7ClG7B9bx5Ax4uKUJX1XM9KKFzZLSI5rolNqP4qsusG0E3GH6OIch70+XONNgZw/w=,iv:m/0LbtvMUWq63Bv+JQSLd7h8u/g8LDRnmGlGRrrT1VY=,tag:7r0jizPcVrdoPPAU8KC/Iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
